### ISSUE TITLE
Installation error for Yuzu EA-3097 and newer

### ISSUE THREAD

**Issue by tonytziorvas** [HiDe-Techno-Tips/yuzu-Early-Access-Launcher#10]
Cannot complete the installation of 3092 / 3097 yuzu. Throws Unhandled exception after finishing downloading the zip file
If i press Continue on the prompt it throws an "attempted to divide by zero" error

Error log:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at SharpCompress.Common.SevenZip.ArchiveReader.ReadDatabase(IPasswordProvider pass)
   at SharpCompress.Archives.SevenZip.SevenZipArchive.LoadFactory(Stream stream)
   at SharpCompress.Archives.SevenZip.SevenZipArchive.<LoadEntries>d__11.MoveNext()
   at SharpCompress.LazyReadOnlyCollection`1.LazyLoader.MoveNext()
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at yuzu_Early_Access_Launcher.Form_yuzuEarlyAccessLauncher.<Extract>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at yuzu_Early_Access_Launcher.Form_yuzuEarlyAccessLauncher.<BackgroundWorker_Download_ProgressChanged>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4515.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
yuzu Early Access Launcher
    Assembly Version: 2.0.2.0
    Win32 Version: 2.0.2.0
    CodeBase: file:///C:/Users/User/AppData/Local/yuzu/yuzu%20Early%20Access%20Launcher.exe
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------

**Comment by HimDek** [comment]
Release coming soon

**Comment by HimDek** [comment]
Fixed and released in [Version 2.0.3](https://github.com/HiDe-Techno-Tips/yuzu-Early-Access-Launcher/releases/tag/v2.0.3)
